changelog:
    exclude:
        labels:
            - internal
    categories:
        - title: New Features & Improvements
          labels:
              - enhancement
              - feature

        - title: Bug Fixes
          labels:
              - bug
              - maintenance

        - title: Documentation
          labels:
              - documentation
              - docs

        - title: Language
          labels:
              - language
              - translation

        - title: Dependencies Updates
          labels:
              - npm dependencies

        - title: Other Changes
          labels:
              - '*'
