name: '🧮 Release'
description: Create a new ticket for a new change release
title: '🧮 [Release] - <type> VERSION <version>'
labels: ['release']
body:
    - type: input
      id: released_date
      attributes:
          label: 'Released Date'
          description: Date of the release
          placeholder: 'day/month/year'
      validations:
          required: false
    - type: textarea
      id: implementation_pr
      attributes:
          label: 'Related Pull Request(s)'
          description: Pull request used for the release that doesn't have a related issue
          placeholder: '- #Pull Request ID'
      validations:
          required: false
    - type: textarea
      id: reference_issues
      attributes:
          label: 'Related Issue(s)'
          description: Common issues related to the release
          placeholder: '- [ ] #Issues IDs'
      validations:
          required: false
    - type: textarea
      id: changed_fixed
      attributes:
          label: 'What has been changed and fixed'
          description: What are the drawbacks/impacts of this release?
          placeholder: Identify the drawbacks and impacts of the release
      validations:
          required: true
    - type: textarea
      id: unresolved_question_or_todos
      attributes:
          label: 'Unresolved questions'
          description: What questions still remain unresolved ?
          placeholder: Identify any unresolved issues.
      validations:
          required: false
