name: first-interaction

on:
    issues:
        types: [opened]
    pull_request_target:
        branches: [dev]
        types: [opened]

jobs:
    check_for_first_interaction:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/first-interaction@main
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  issue-message: |
                      👋 Hey buddy. Thank you for opening your first issue here.

                      You may have already selected the right issue category (Bug, change or feature request). Please take a second look. Thank you!
                      To check if everthing alright please check our CODE OF CONDUCT [here](https://github.com/Mittelbots/Mittelbot/blob/a6a0831fb6ba92e0641c5f764dfa63a818c3e4ca/CODE_OF_CONDUCT.md) and hit the checkbox if you have read them.

                      - [ ] I have read and understood the CODE OF CONDUCT
                      - [ ] I have read and understood the [CONTRIBUTING.md](https://github.com/Mittelbots/Mittelbot/blob/a6a0831fb6ba92e0641c5f764dfa63a818c3e4ca/CONTRIBUTING.md)

                  pr-message: |
                      Wow! Thank you for being here and helping this project to grow.

                      Check our CODE OF CONDUCT [here](https://github.com/Mittelbots/Mittelbot/blob/a6a0831fb6ba92e0641c5f764dfa63a818c3e4ca/CODE_OF_CONDUCT.md) and hit the checkbox if you have read them.

                      - [ ] I have read and understood the CODE OF CONDUCT
                      - [ ] I have read and understood the [CONTRIBUTING.md](https://github.com/Mittelbots/Mittelbot/blob/a6a0831fb6ba92e0641c5f764dfa63a818c3e4ca/CONTRIBUTING.md)
